### ISSUE TITLE
converter to dataless is not able to handle <Sensor> <Description>

### ISSUE THREAD

**Issue by chad-iris** [iris-edu/stationxml-seed-converter#1]
From SeisCode (issue 906):

The following IRIS station service query:

    http://service.iris.edu/fdsnws/station/1/query?net=AK&sta=CAPN&loc=*&cha=BDO&level=response&format=xml&includecomments=true&nodata=404

contains <Sensor> <Description> tags and an attempt to convert it to dataless using:

    java -jar stationxml-converter.jar

produces the following error:

    edu.iris.Fissures.seed.exception.SeedInputException: input string has too many fields for blockette 33
    at edu.iris.Fissures.seed.container.Blockette.setTokenString(Blockette.java:1987)
    at edu.iris.Fissures.seed.container.Blockette.initialize(Blockette.java:180)
    at edu.iris.Fissures.seed.container.Blockette.<init>(Blockette.java:90)
    at edu.iris.Fissures.seed.container.BlocketteFactory.createBlockette(BlocketteFactory.java:65)
    at edu.iris.Fissures.seed.builder.SeedObjectBuilder.build(SeedObjectBuilder.java:298)
    at edu.iris.converter.SeedPrinter.do33(SeedPrinter.java:692)
    at edu.iris.converter.SeedPrinter.doChannels(SeedPrinter.java:265)
    at edu.iris.converter.SeedPrinter.build(SeedPrinter.java:208)
    at edu.iris.converter.SeedPrinter.process(SeedPrinter.java:115)
    at edu.iris.converter.Main.<init>(Main.java:197)
    at edu.iris.converter.Main.main(Main.java:216)
    edu.iris.Fissures.seed.exception.SeedInputException: input string has too many fields for blockette 33

If we remove the <Sensor> tag, then it works fine!

**Comment by timronan** [comment]
This error does not occur in the new converter. Refer to [seed-xml-converter](https://github.com/iris-edu/seed-xml-converter)
