### ISSUE TITLE
Pole numbers are incorrectly indexed when converting from SEED to XML

### ISSUE THREAD

**Issue by jholland-usgs** [iris-edu/stationxml-seed-converter#25]
Tested by converting the IRIS produced IU.dataless (and both ASL and SIS produced dataless). I was using the 2.0.3 snapshot.

The indexing appears to persist after zeros are written. See below. (I have stripped out irrelevant portions)

```xml
<Zero number="0">
...
</Zero>
<Zero number="1">
...
</Zero>
<Pole number="2">
...
</Pole>
<Pole number="3">
</Pole>
```

Expected behavior:

```xml
<Zero number="0">
...
</Zero>
<Zero number="1">
...
</Zero>
<Pole number="0">
...
</Pole>
<Pole number="1">
</Pole>
```

**Comment by timronan** [comment]
We verified this issue and will begin working on it promptly. 

```
<Zero number="0">
...
</Zero>
<Zero number="1">
...
 </Zero>
<Pole number="2">
...
</Pole>
<Pole number="3">
...
</Pole>
```

**Comment by jholland-usgs** [comment]
Thank you

**Comment by jholland-usgs** [comment]
Any update on this issue?
Thanks

**Comment by timronan** [comment]
A new converter version, 2.0.4-SNAPSHOT, has been released. Please find the jar at [https://github.com/iris-edu/stationxml-seed-converter/releases](https://github.com/iris-edu/stationxml-seed-converter/releases). We addressed this issue in commit 4dee8706b704120596ff977efb74b4bc864e7d0d. Please test this issue using the new jar.

**Comment by jholland-usgs** [comment]
I am unable to test this issue as I am getting a new exception when converting IU.dataless (from IRIS).

```
java -jar stationxml-seed-converter.jar --input /APPS/metadata/SEED/IU.dataless --output xml/iu.xml
May 08, 2019 1:14:30 PM edu.iris.dmc.seed.builder.BlocketteBuilder build010
INFO: Building: 010010302.4121988,001,00:00:00.0000~2599,365,23:59:59.0000~2019,126,09:47:00.0000~IRIS-DMC~IU.dataless~
May 08, 2019 1:14:52 PM edu.iris.dmc.seed.io.RecordInputStream next
INFO: Expected 8 but read only -1 bytes
May 08, 2019 1:14:53 PM edu.iris.dmc.station.Application exitWithError
SEVERE: 
Error: edu.iris.dmc.station.mapper.MetadataConverterException: edu.iris.dmc.unit.InvalidUnitException: Unkown unit :C



Error: edu.iris.dmc.station.mapper.MetadataConverterException: edu.iris.dmc.unit.InvalidUnitException: Unkown unit :C


Usage:
java -jar stationxml-converter.jar [arguments]
	-h, aliases = "--help", usage = "print this message"
	--input, usage = "Input as a file or URL"
	--output, usage = "Output file path and name"

```

**Comment by timronan** [comment]
This bug was fixed by commit 847edc702c267ccc74afadb86a31d878cdc3c55c. Please pull the updated jar from releases, or pull the code and build a new jar and try your test again. Thanks for testing. The stdout should be suppressed as well.

**Comment by jholland-usgs** [comment]
Thanks for the fast response, I will try again once the new jar is published.

**Comment by jholland-usgs** [comment]
When should I expect 2.0.5 to be released with this fix?

Thank you,

James

**Comment by jholland-usgs** [comment]
I was able to build the jar locally, but had to skip running unit tests because of the below exception. I will test the original issue now.

```
[INFO] Running edu.iris.dmc.station.converter.UsgsAnmoConverterTest
java.lang.NullPointerException
	at edu.iris.dmc.station.converter.UsgsAnmoConverterTest.compare(UsgsAnmoConverterTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by timronan** [comment]
We are in progress of testing recently added patches. We will update the junit test promptly,  a new jar is excepted to be released in the next few days.

**Comment by jholland-usgs** [comment]
I have been able to test and no longer reproduce the original issue with this ticket.

Thank you for fixing the pole numbering issue. I will close this issue now.

**Comment by timronan** [comment]
Thank you for working with us.
