### ISSUE TITLE
Cannot parse certain dates that look o.k.

### ISSUE THREAD

**Issue by ketchum-usgs** [iris-edu/stationxml-seed-converter#27]
The attached statoin XML file throws an error on a line that looks like:
grep 2019-05-29T01:46:06.90491 TXMB01.xml 
  <Created>2019-05-29T01:46:06.90491</Created>
Which does not appear to be badly formatted.

acqdb::ketchum:XMLIMPORT>java -jar ~vdl/bin/stationxml-seed-converter-2.0.5-SNAPSHOT.jar --input ~metadata/XMLIMPORT/TXMB01.xml --output TXMB01.dataless
java.time.format.DateTimeParseException: Text '2019-05-29T01:46:06.90491' could not be parsed, unparsed text found at index 23
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1952)
	at java.time.format.DateTimeFormatter.parseBest(DateTimeFormatter.java:1897)
	at edu.iris.dmc.fdsn.station.model.ZonedDateTimeXmlAdapter.unmarshal(ZonedDateTimeXmlAdapter.java:33)
	at edu.iris.dmc.fdsn.station.model.ZonedDateTim
[TXMB01.txt](https://github.com/iris-edu/stationxml-seed-converter/files/3234242/TXMB01.txt)
eXmlAdapter.unmarshal(ZonedDateTimeXmlAdapter.java:15)
	at com.sun.xml.bind.v2.runtime.reflect.AdaptedAccessor.set(AdaptedAccessor.java:85)
	at com.sun.xml.bind.v2.runtime.reflect.TransducedAccessor$CompositeTransducedAccessorImpl.parse(TransducedAccessor.java:239)
	at com.sun.xml.bind.v2.runtime.unmarshaller.LeafPropertyLoader.text(LeafPropertyLoader.java:65)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.text(UnmarshallingContext.java:590)
	at com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.processText(SAXConnector.java:213)
	at com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.endElement(SAXConnector.java:176)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:258)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:229)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:204)
	at edu.iris.dmc.IrisUtil.readXml(IrisUtil.java:43)
	at edu.iris.dmc.IrisUtil.readXml(IrisUtil.java:36)
	at edu.iris.dmc.station.converter.XmlToSeedFileConverter.convert(XmlToSeedFileConverter.java:407)
	at edu.iris.dmc.station.converter.XmlToSeedFileConverter.convert(XmlToSeedFileConverter.java:65)
	at edu.iris.dmc.station.Application.convert(Application.java:117)
	at edu.iris.dmc.station.Application.run(Application.java:73)
	at edu.iris.dmc.station.Application.main(Application.java:24)
May 29, 2019 7:51:44 PM edu.iris.dmc.station.Application exitWithError
SEVERE: 

[TXMB01.txt](https://github.com/iris-edu/stationxml-seed-converter/files/3234247/TXMB01.txt)

**Comment by timronan** [comment]
This issue has been addressed by commit [d3db482e8cd94df8392693bebe669e66875d8fae](https://github.com/yazan-iris/fdsn-stationxml-model/commit/d3db482e8cd94df8392693bebe669e66875d8fae)
 in the [fdsn-stationxml-model](https://github.com/yazan-iris/fdsn-stationxml-model). The Github releases directory has also been updated. Please get or compile the new jar and rerun the test.

The TXMB01.xml file has one or multiple FIR response blockettes which lengths exceed 9,999 characters and are instead 16872 characters. The Seed manual states:

>  Blockette could exceed the maximum of 9,999 characters. If so, continue on the next record. Field 4 should be set the same, but fields 5 — 7 in subsequent blockettes should be ignored.****

Although this is separate from the original issue, the stationxml-seed-converter needs to be updated to handle this edge case.

**Comment by timronan** [comment]
Both issues have been resolved. Please refer to issue #30 if concerned about the FIR continuation blockette issue. Please take the updated jar file from the release directory and rerun your test. Thank you for bringing these issues to our attention.
